// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBypZYCnHFnF5SgR5TX_h_VyxakHuCuQ7s',
    appId: '1:94709603331:web:2add23a898952781cf8236',
    messagingSenderId: '94709603331',
    projectId: 'chatapp-c6355',
    authDomain: 'chatapp-c6355.firebaseapp.com',
    storageBucket: 'chatapp-c6355.firebasestorage.app',
    measurementId: 'G-HHQWE71MV9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs_cHjAKVS8Sqf3PQevdB2EY_iWe32c_Q',
    appId: '1:94709603331:android:acaccb4be601d1f6cf8236',
    messagingSenderId: '94709603331',
    projectId: 'chatapp-c6355',
    storageBucket: 'chatapp-c6355.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2SPHysDP04RIqoNjKKzfYkq1agUsXI5w',
    appId: '1:94709603331:ios:46f46162eae5deb8cf8236',
    messagingSenderId: '94709603331',
    projectId: 'chatapp-c6355',
    storageBucket: 'chatapp-c6355.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2SPHysDP04RIqoNjKKzfYkq1agUsXI5w',
    appId: '1:94709603331:ios:46f46162eae5deb8cf8236',
    messagingSenderId: '94709603331',
    projectId: 'chatapp-c6355',
    storageBucket: 'chatapp-c6355.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBypZYCnHFnF5SgR5TX_h_VyxakHuCuQ7s',
    appId: '1:94709603331:web:2e582eadae63d7e5cf8236',
    messagingSenderId: '94709603331',
    projectId: 'chatapp-c6355',
    authDomain: 'chatapp-c6355.firebaseapp.com',
    storageBucket: 'chatapp-c6355.firebasestorage.app',
    measurementId: 'G-HYBMFQLTEG',
  );

}